# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.since_file: 'var/sinceDateTime'

    crm.api_url: '%env(CRM_API_URL)%'
    crm.api_key: '%env(CRM_API_KEY)%'

    crm.custom_fields:
        date: '%env(CRM_DATE_FIELD)%'
        time: '%env(CRM_TIME_FIELD)%'
    crm.site: '%env(CRM_SITE_CODE)%'

    dentalink.api_url: 'https://api.dentalink.healthatom.com/api/v1/'
    dentalink.api_token: '%env(DENTALINK_API_TOKEN)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    monolog.formatter.pretty:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"
            - "Y-m-d H:i:s"
            - false
            - true