# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
imports:
    - { resource: resources/ }

parameters:
    app.since_datetime_file_citas: 'var/citasSinceDateTime'
    app.since_datetime_file_payments: 'var/paymentsSinceDateTime'
    app.since_id_file_customers: 'var/customersSinceId'
    app.since_id_file_orders: 'var/ordersSinceId'

    app.status_mapping: '%env(string:STATUS_MAPPING)%'
    app.custom_fields: '%env(string:CUSTOM_FIELDS)%'

    crm.api_url: '%env(string:CRM_API_URL)%'
    crm.api_key: '%env(string:CRM_API_KEY)%'

    crm.dentalink_id_field: '%env(string:CRM_DENTALINK_ID_FIELD)%'
    crm.site: '%env(string:CRM_SITE_CODE)%'
    crm.payment_type: '%env(string:CRM_PAYMENT_TYPE)%'

    dentalink.api_url: 'https://api.dentalink.healthatom.com/api/v1/'
    dentalink.api_token: '%env(string:DENTALINK_API_TOKEN)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    monolog.formatter.pretty:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"
            - "Y-m-d H:i:s"
            - true
            - true

    App\Service\Dentalink\Factory\Factory:
        class: 'App\Service\Dentalink\Factory\Factory'
        arguments:
            $httpClient: '@http_client_dentalink.guzzle'

    App\Service\Simla\ApiWrapper:
        class: 'App\Service\Simla\ApiWrapper'
        arguments:
            $httpClient: '@http_client_simla.guzzle'